title: Afahri Kerr
email: AfahriAKerr91@Gmail.com
logo: /assets/img/FaceShot.jpg
description: Southern New Hampshire University<br>
  Bachelor of Science Computer Science<br>
  Graduation - December 2023<br>
  GPA - 4.0<br><br>
  I am always looking for new projects and opportunities to improve my skills so send me a message if you would like to collaborate.<br><br>
  Email - <a href="mailto:AfahriAKerr91@gmail.com">AfahriAKerr91@Gmail.com</a><br>
  LinkedIn - <a href="https://www.linkedin.com/in/afahri-kerr/">Afahri Kerr</a><br>
  Twitter - <a href="https://twitter.com/AfahriKerr">@AfahriKerr</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AfahriKerr
github_username:  AfahriOK
show_downloads: false
# Build settings
theme: jekyll-theme-minimal
