title: Afahri Kerr
email: AfahriAKerr91@Gmail.com
logo: /assets/img/FaceShot.jpg
description: >- # this means to ignore newlines until "baseurl:"
  I started my computer science journey in February of 2022 and 
  created this portfolio to showcase my growth. I started with absolutely
  0 experience so not everything will be perfect but you can definitely see
  where I have improved.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AfahriKerr
github_username:  AfahriOK
show_downloads: false

# Build settings
theme: jekyll-theme-minimal
