title: Afahri Kerr
email: AfahriAKerr91@Gmail.com
logo: /assets/img/FaceShot.jpg
description: |
  Computer Science Student         
  Southern New Hampshire University
  Bachelor of Science Computer Science
  Graduation - December 2023
  GPA - 4.0
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AfahriKerr
github_username:  AfahriOK
show_downloads: false
# Build settings
theme: jekyll-theme-minimal
